#!/usr/bin/env python3
"""Amalgamate the qvf-writer C++ library into a single drop-in header.

Produces ``cpp/qvf_single.hpp``: an STB-style single-file library. Declarations
are always visible; the implementation compiles only in the one translation unit
that does ``#define QVF_IMPLEMENTATION`` before including the header.

Usage:
    python qvf-writer/scripts/amalgamate.py            # writes cpp/qvf_single.hpp
    python qvf-writer/scripts/amalgamate.py --check     # exit 1 if out of date

The generated header is committed so adopters can grab one file; this script is
the source of truth, and make_archive.sh / a drift check keep them in sync.
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CPP = os.path.normpath(os.path.join(HERE, "..", "cpp"))
OUT = os.path.join(CPP, "qvf_single.hpp")

# Local project includes to strip (already inlined); system <...> includes stay.
_LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"(qvf/)?[A-Za-z0-9_./]+"\s*$')


def _strip_local_includes(text: str) -> str:
    return "\n".join(
        line for line in text.splitlines() if not _LOCAL_INCLUDE.match(line)
    )


def _read(rel: str) -> str:
    with open(os.path.join(CPP, rel), "r", encoding="utf-8") as fh:
        return fh.read()


def build() -> str:
    parts: list[str] = []
    parts.append(
        "// qvf_single.hpp — single-header amalgamation of the qvf-writer C++\n"
        "// library (Apache-2.0). GENERATED by scripts/amalgamate.py — do not edit\n"
        "// by hand; edit the sources under cpp/ and regenerate.\n"
        "//\n"
        "// Usage (STB-style): in exactly ONE .cpp translation unit,\n"
        "//     #define QVF_IMPLEMENTATION\n"
        "//     #include \"qvf_single.hpp\"\n"
        "// and just #include \"qvf_single.hpp\" everywhere else. Zero external\n"
        "// dependencies; C++17. See the QVF spec + library guide for the API.\n"
        "#ifndef QVF_SINGLE_HPP\n#define QVF_SINGLE_HPP\n"
    )

    # --- always-visible declarations (writer + reader public API) --------
    parts.append("\n// ===== qvf/json.hpp =====\n")
    parts.append(_read("include/qvf/json.hpp"))
    for rel in ("include/qvf/qvf.hpp", "include/qvf/qvf_reader.hpp"):
        parts.append(f"\n// ===== {rel} (public API) =====\n")
        parts.append(_strip_local_includes(_read(rel)))

    # --- implementation, compiled once -----------------------------------
    parts.append("\n#ifdef QVF_IMPLEMENTATION\n")
    for rel in ("src/qvf_sha256.hpp", "src/qvf_deflate.hpp", "src/qvf_inflate.hpp",
                "src/qvf_zip.hpp", "src/qvf_unzip.hpp"):
        parts.append(f"\n// ===== {rel} =====\n")
        parts.append(_strip_local_includes(_read(rel)))
    for rel in ("src/qvf.cpp", "src/qvf_reader.cpp"):
        parts.append(f"\n// ===== {rel} =====\n")
        parts.append(_strip_local_includes(_read(rel)))
    parts.append("\n#endif  // QVF_IMPLEMENTATION\n")

    parts.append("\n#endif  // QVF_SINGLE_HPP\n")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    content = build()
    if "--check" in argv:
        if not os.path.exists(OUT):
            print("qvf_single.hpp missing; run amalgamate.py", file=sys.stderr)
            return 1
        with open(OUT, encoding="utf-8") as fh:
            current = fh.read()
        if current != content:
            print("qvf_single.hpp is out of date; run amalgamate.py", file=sys.stderr)
            return 1
        print("qvf_single.hpp is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {OUT} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
